### ISSUE TITLE
[ERROR] [1659417875.901826476]: PluginlibFactory: The plugin for class 'autoware_rviz_debug/DecisionMakerPanel' failed to load.

### ISSUE THREAD

**Issue by abhishekt711** [rsasaki0109/lidar_localizer#9]
![image](https://user-images.githubusercontent.com/36338604/182532756-787c7d29-78a4-4387-994f-b7d0307202b4.png)

**Comment by rsasaki0109** [comment]
That error is coming from autoware's planning-related visualization plugin not loading, and there is nothing wrong with the operation of this localization package.

**Comment by abhishekt711** [comment]
Yes. Can you please provide the solution for this. How to load the auto ware visualisation plugin? Or can we use this package without using auto ware visualisation plugin ?

**Comment by rsasaki0109** [comment]
I am not currently developing this package and do not intend to address this issue.
Perhaps we could remove the relevant items from the rviz file, but it is a bit tedious.
Pull requests are always welcome.

**Comment by rsasaki0109** [comment]
I have determined that the issue has been resolved and will close this issue.

**Comment by hyff0088** [comment]
sudo apt-get install  ros-kinetic-jsk-visualization
